version: "1.0"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/data
    links:
      - 3.10.0a3-slim-buster
  debian:
    image: 3.10.0a3-slim-buster
volumes:
  logvolume01: {}
