version: '3'

services:

  wave:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - WAVE_VERSION=0.10.0
    container_name: wave
    volumes:
      - ./code:/code
    ports:
      - "10101:10101"